// File generated by FlutterFire CLI.
// This is a placeholder file. To generate the actual configuration:
//
// 1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
// 2. Run: flutterfire configure
// 3. This file will be automatically replaced with your Firebase config.
//
// See: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Replace these placeholder values by running:
    //   flutterfire configure
    //
    // This will auto-generate the correct configuration for your
    // Firebase project and platform.

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDduf13vr1dlQ5OWiJ-jAXh09eaQtOmmn8',
    appId: '1:383311248166:android:b82694c0ba2047c4291fe7',
    messagingSenderId: '383311248166',
    projectId: 'myduitgweh',
    storageBucket: 'myduitgweh.firebasestorage.app',
  );

  // ⚠️ PLACEHOLDER VALUES - Replace with `flutterfire configure`

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIAK0FUg713fXNcmIitkVuftOqlkKD3UA',
    appId: '1:383311248166:ios:b7fccba3d99bde88291fe7',
    messagingSenderId: '383311248166',
    projectId: 'myduitgweh',
    storageBucket: 'myduitgweh.firebasestorage.app',
    iosBundleId: 'com.myduitgweh.myDuitGweh',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'YOUR-STORAGE-BUCKET',
    authDomain: 'YOUR-AUTH-DOMAIN',
  );
}
